name: RPM Build
on:
  pull_request:
    branches: 
      - main
      - rpm-builder-action
  push:
    branches: 
      - main
      - rpm-builder-action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Custom rpm building from Derek to build RPM
      - uses: djw8605/docker-mock-rpmbuilder@master
        with:
          spec-file: rpm/scitokens-cpp.spec
          mock-config: epel-9-x86_64
          